services:
  pb:
    container_name: "pocketbase"
    image: dhhdev/pocketbase:v0.26.5
    restart: unless-stopped
    ports:
      - 8080:8080
    volumes:
      - ./pb/data:/pb/pb_data
      - ./pb/hooks:/pb/pb_hooks
      - ./pb/migrations:/pb/pb_migrations